import { 
  Smartphone, 
  Plus, 
  CreditCard, 
  Globe, 
  ShoppingCart, 
  User, 
  ShieldCheck, 
  Settings, 
  MessageSquare, 
  MapPin,
  Wifi,
  Tv,
  HelpCircle,
  FileText,
  DollarSign,
  Package,
  Activity,
  Zap,
  RefreshCcw,
  Truck,
  Layers,
  Search,
  CheckCircle2,
  Gamepad,
  Watch,
  Headset,
  HardDrive
} from 'lucide-react';

export interface TagComponent {
  componentId: string;
  componentType: 'Button' | 'Form Field' | 'CTA' | 'Link' | 'Modal' | 'Input' | 'Section';
  componentLabel: string;
  aiRecommendedTag: string;
  eventType: 'click' | 'submit' | 'view' | 'interaction' | 'change';
  priority: 'High' | 'Medium' | 'Low';
  recommendationReason: string;
  businessValue: string;
  approvalState: 'Proposed' | 'Approved' | 'Rejected' | 'Excluded';
  confidence: 'High' | 'Medium' | 'Low';
  level: 'Page' | 'Component' | 'Interaction';
  currentTracking: string;
  recommendedTracking: string;
  analyticsDestination: 'Adobe Analytics' | 'AEP' | 'Both';
  // New key-value data model for enterprise analytics
  dataLayer: Record<string, string>;
  // AI feedback and observability metadata
  rejectionReason?: string;
  rejectionReasonLabel?: string;
  rejectionContext?: string;
  rejectionScope?: 'local' | 'global';
  rejectionDate?: string;
  isModified?: boolean;
  // Hidden observability metadata
  aiMetadata?: {
    contextSourceIds?: string[];
    businessRulesApplied?: string[];
    confidenceScore?: number;
    feedbackHistory?: any[];
    modelVersion?: string;
    analysisRunId?: string;
  };
}

export interface JourneyStep {
  stepId: string;
  stepName: string;
  stepType: 'view' | 'action';
  screenType: 'Page' | 'Modal' | 'Component group' | 'Interaction';
  screenTemplate: 'landing' | 'config' | 'form' | 'review' | 'success';
  description: string;
  userIntent?: string;
  priority: 'Critical' | 'Optional';
  criticalFlag: boolean; 
  interactionType: 'View' | 'Click' | 'Form submit' | 'External redirect' | 'Interaction';
  anchorType?: 'Page URL' | 'CSS selector' | 'Component name' | 'Screenshot reference';
  anchorValue?: string;
  identificationMethod?: 'Page URL match' | 'Component selector' | 'DOM interaction' | 'Heuristic inference';
  confidence?: 'High' | 'Medium' | 'Low';
  screenshotReference?: string;
  relatedComponent?: string;
  components?: TagComponent[];
  isSynced?: boolean;
  currentTrackingStatus?: 'Page view only' | 'Click event on CTA' | 'No tracking' | 'Form detected';
  improvementHint?: string;
}

export interface JiraContext {
  ticketId: string;
  title: string;
  reference: string;
  description: string;
  acceptanceCriteria: string[];
}

export interface Journey {
  journeyId: string;
  journeyName: string;
  platform: 'Web' | 'Mobile' | 'Hybrid';
  environmentLink: string;
  trackingFocus: 'Conversion' | 'Engagement' | 'Drop-off reduction' | 'Retention' | 'Service';
  autoGeneratedGoal: string;
  goalConfidence?: 'High' | 'Medium' | 'Low';
  source?: string;
  sourceType?: 'System' | 'Figma' | 'Jira';
  detectionScope?: string;
  status: 'Not started' | 'In progress' | 'Artifact generated' | 'Completed';
  lastUpdated: string;
  lastUpdatedBy: string;
  metrics: {
    label: string;
    value: string;
  }[];
  icon: any;
  category: string;
  steps: JourneyStep[];
  tagRecommendationCount: number;
  jiraContext?: JiraContext;
}

export interface JiraTicket {
  ticketId: string;
  journeyName: string;
  title: string;
  description: string;
  acceptanceCriteria: string[];
  status: 'New' | 'Needs Context' | 'Ready for Analysis' | 'In Review' | 'Analyzing' | 'Processing' | 'Ready for Review' | 'Reviewed';
  assignedTo: string;
  createdDate: string;
  dueDate: string;
  priority: 'High' | 'Medium' | 'Low';
  platform: 'Web' | 'Mobile' | 'Hybrid';
  category: string;
  environmentLink?: string;
  attachments?: Array<{
    name: string;
    type: 'meeting_notes' | 'recording' | 'documentation' | 'other';
    url: string;
  }>;
  contextNotes?: string;
  analysisCompletedDate?: string;
  aiConfidenceSummary?: {
    high: number;
    medium: number;
    low: number;
  };
  tagCount?: number;
  linkedJourneyId?: string; // Link to generated journey after analysis
}

const getContextualStepNames = (journeyName: string): string[] => {
  const n = journeyName.toLowerCase();
  
  if (n.includes('login') || n.includes('secure') || n.includes('portal') || n.includes('identity')) {
    return ['Login Entry', 'MFA Verification', 'Security Questions', 'Identity Verified', 'Dashboard Access'];
  }
  if (n.includes('upgrade') || n.includes('device') || n.includes('watch') || n.includes('phone')) {
    return ['Promotion Landing', 'Device Selection', 'Color & Storage', 'Protection Plan', 'Trade-in Details', 'Order Review', 'Order Confirmed'];
  }
  if (n.includes('activation') || n.includes('onboarding') || n.includes('setup') || n.includes('onboard')) {
    return ['Welcome Screen', 'Identity Check', 'Account Linking', 'Service Configuration', 'Final Setup', 'Activation Success'];
  }
  if (n.includes('search') || n.includes('discovery') || n.includes('nav') || n.includes('guide')) {
    return ['Homepage Discovery', 'Search Results', 'Category Filter', 'Product Comparison', 'Detail View', 'Selection Finalized'];
  }
  if (n.includes('bill') || n.includes('pay') || n.includes('cart') || n.includes('checkout')) {
    return ['Payment Overview', 'Card Selection', 'Auto-pay Opt-in', 'Transaction Review', 'Receipt & Done'];
  }
  if (n.includes('support') || n.includes('chat') || n.includes('return') || n.includes('troubleshoot')) {
    return ['Support Landing', 'Inquiry Category', 'Details Entry', 'Agent Interaction', 'Resolution Summary', 'Survey'];
  }
  if (n.includes('plan') || n.includes('line') || n.includes('unlimited') || n.includes('fios') || n.includes('internet')) {
    return ['Plan Comparison', 'Address Check', 'Line Assignment', 'Optional Add-ons', 'Summary Review', 'Service Confirmed'];
  }
  
  // Default logical flow
  return ['Introduction', 'Configuration', 'Details', 'Review', 'Completion'];
};

const getScreenTemplate = (stepName: string): 'landing' | 'config' | 'form' | 'review' | 'success' => {
  const s = stepName.toLowerCase();
  if (s.includes('landing') || s.includes('welcome') || s.includes('intro') || s.includes('homepage') || s.includes('hub')) return 'landing';
  if (s.includes('select') || s.includes('choice') || s.includes('compare') || s.includes('filter') || s.includes('config') || s.includes('option')) return 'config';
  if (s.includes('check') || s.includes('input') || s.includes('enter') || s.includes('form') || s.includes('identity') || s.includes('mfa') || s.includes('detail') || s.includes('login')) return 'form';
  if (s.includes('review') || s.includes('summary') || s.includes('overview') || s.includes('interaction')) return 'review';
  if (s.includes('success') || s.includes('confirm') || s.includes('receipt') || s.includes('done') || s.includes('verified') || s.includes('resolution')) return 'success';
  return 'landing';
};

const generateRealisticComponents = (stepName: string, journeyName: string, count: number): TagComponent[] => {
  const s = stepName.toLowerCase();
  const j = journeyName.toLowerCase();
  
  // Logical component types based on step intent
  const getContextualType = (idx: number) => {
    if (s.includes('select') || s.includes('choice') || s.includes('plan')) return idx % 2 === 0 ? 'CTA' : 'Button';
    if (s.includes('input') || s.includes('form') || s.includes('mfa') || s.includes('login')) return idx % 2 === 0 ? 'Input' : 'Button';
    if (s.includes('landing') || s.includes('intro')) return idx % 2 === 0 ? 'Link' : 'CTA';
    return idx % 3 === 0 ? 'Button' : (idx % 3 === 1 ? 'CTA' : 'Link');
  };

  const getContextualLabel = (type: string, idx: number) => {
    if (s.includes('device')) return `${type === 'Input' ? 'IMEI Input' : 'Select Device'} ${idx + 1}`;
    if (s.includes('payment') || s.includes('bill')) return `${type === 'Input' ? 'Card Number' : 'Pay Now'} ${idx + 1}`;
    if (s.includes('login') || s.includes('identity')) return `${type === 'Input' ? 'User ID Field' : 'Continue'} ${idx + 1}`;
    if (s.includes('review')) return `${type === 'Button' ? 'Confirm Action' : 'Edit Section'} ${idx + 1}`;
    if (s.includes('search')) return `${type === 'Input' ? 'Search Query' : 'Filter Toggle'} ${idx + 1}`;
    return `${stepName} ${type} ${idx + 1}`;
  };

  // Generate contextual key-value data based on step and journey
  // IMPORTANT: Only component-level attributes, NO page-level data
  const getDataLayerForComponent = (stepName: string, journeyName: string, type: string, idx: number, label: string): Record<string, string> => {
    const s = stepName.toLowerCase();
    const j = journeyName.toLowerCase();
    
    // Component-level base attributes (NOT page-level)
    const baseData: Record<string, string> = {
      element_label: label,
      element_type: type,
      element_position: (idx + 1).toString(),
      interaction_type: type === 'Input' ? 'form_input' : 'click',
      event_action: type === 'Input' ? 'field_change' : 'button_click',
    };

    // Add contextual data based on step type
    if (s.includes('device') || s.includes('selection') || s.includes('choice')) {
      return {
        ...baseData,
        product_name: idx === 0 ? 'iPhone 15 Pro' : idx === 1 ? 'Samsung Galaxy S24' : 'Google Pixel 8',
        product_price: idx === 0 ? '999' : idx === 1 ? '899' : '799',
        product_color: idx === 0 ? 'Natural Titanium' : idx === 1 ? 'Phantom Black' : 'Obsidian',
        product_storage: idx === 0 ? '256GB' : '128GB',
        product_sku: `SKU-${idx + 1000}`,
      };
    }
    
    if (s.includes('plan') || s.includes('unlimited') || s.includes('line')) {
      return {
        ...baseData,
        plan_name: idx === 0 ? 'Unlimited Plus' : 'Unlimited Welcome',
        plan_price: idx === 0 ? '80' : '65',
        plan_type: 'postpaid',
        line_count: '1',
        plan_tier: idx === 0 ? 'premium' : 'standard',
      };
    }
    
    if (s.includes('payment') || s.includes('bill') || s.includes('checkout')) {
      return {
        ...baseData,
        payment_method: 'credit_card',
        payment_type: idx === 0 ? 'one_time' : 'recurring',
        transaction_amount: '99.99',
        currency: 'USD',
        payment_processor: 'stripe',
      };
    }

    if (s.includes('protection') || s.includes('add-on')) {
      return {
        ...baseData,
        addon_name: idx === 0 ? 'Device Protection' : 'AppleCare+',
        addon_price: idx === 0 ? '17' : '12.99',
        addon_type: 'insurance',
        addon_coverage: idx === 0 ? 'comprehensive' : 'standard',
      };
    }

    // Default component-level data
    return baseData;
  };
  
  return Array.from({ length: count }).map((_, i) => {
    const type = getContextualType(i) as any;
    const event = type === 'Input' ? 'change' : 'click';
    const label = getContextualLabel(type, i);
    const tagBase = journeyName.toLowerCase().replace(/\s/g, '.');
    const stepBase = stepName.toLowerCase().replace(/\s/g, '.');
    
    return {
      componentId: `c-${Math.random().toString(36).substr(2, 9)}`,
      componentType: type,
      componentLabel: label,
      aiRecommendedTag: `vzw.cx.${tagBase}.${stepBase}.${type.toLowerCase()}.${i + 1}`,
      eventType: event,
      priority: i === 0 ? 'High' : 'Medium',
      recommendationReason: `AI identified this ${type} as a critical path element for ${stepName} in the ${journeyName} journey.`,
      businessValue: i === 0 ? 'Conversion Driver' : 'Operational Insight',
      approvalState: 'Proposed',
      confidence: i === 0 ? 'High' : 'Medium',
      level: 'Component',
      currentTracking: 'No tracking',
      recommendedTracking: `vzw.event.${event}`,
      analyticsDestination: 'Both',
      // New key-value data model for enterprise analytics
      dataLayer: getDataLayerForComponent(stepName, journeyName, type, i, label)
    };
  });
};

const generateRealisticSteps = (journeyName: string, totalTargetTags: number): JourneyStep[] => {
  const stepNames = getContextualStepNames(journeyName);
  const stepCount = stepNames.length;
  const tagsPerStep = Math.ceil(totalTargetTags / stepCount);
  
  const getRichDescription = (name: string, index: number, total: number): string => {
    const s = name.toLowerCase();
    const j = journeyName.toLowerCase();
    
    if (s.includes('login') || s.includes('entry')) return `Main authentication interface for ${journeyName}. Featuring secure credentials entry with corporate branding and system access links.`;
    if (s.includes('mfa') || s.includes('verify')) return `Secondary security challenge for ${journeyName}. Users must enter a 6-digit synchronization code sent to their registered device to proceed.`;
    if (s.includes('verified') || s.includes('success') || s.includes('done') || s.includes('confirmed')) return `Final success state for ${journeyName}. Displays confirmation of completed actions, transaction IDs, and provides immediate next-step navigation.`;
    if (s.includes('landing') || s.includes('welcome')) return `Entry point for ${journeyName}. High-level overview of value propositions and a clear call-to-action to begin the flow.`;
    if (s.includes('select') || s.includes('choice') || s.includes('config')) return `Comparison and selection surface. Interactive cards allow users to evaluate different levels of service for ${journeyName}.`;
    if (s.includes('trade-in')) return `Valuation engine where users provide device condition details to calculate credit towards their ${journeyName} request.`;
    if (s.includes('bill') || s.includes('pay')) return `Financial summary showing current balances, upcoming charges, and primary payment method selection for ${journeyName}.`;
    if (s.includes('review') || s.includes('check')) return `Pre-submission summary. Final data validation screen where all previous selections are presented for one last verification.`;
    if (s.includes('details') || s.includes('input') || s.includes('form')) return `Detailed data ingestion phase. Capturing critical user information including names, emails, and addresses required for ${journeyName}.`;
    
    return `Specialized ${name} stage within the ${journeyName} sequence. Focusing on step ${index + 1} of the end-to-end user experience.`;
  };

  return stepNames.map((name, i) => {
    const components = generateRealisticComponents(name, journeyName, Math.min(6, Math.max(2, tagsPerStep)));
    const template = getScreenTemplate(name);
    const richDesc = getRichDescription(name, i, stepCount);
    
    return {
      stepId: `step-${i + 1}-${Math.random().toString(36).substr(2, 5)}`,
      stepName: name,
      stepType: i % 2 === 0 ? 'view' : 'action',
      screenType: template === 'landing' ? 'Page' : 'Component group',
      screenTemplate: template,
      priority: i === 0 || i === stepCount - 1 ? 'Critical' : 'Optional',
      description: richDesc, // Now much more detailed and contextual
      userIntent: `Successfully complete ${name.toLowerCase()}`,
      criticalFlag: i === 0 || i === stepCount - 1,
      interactionType: template === 'form' ? 'Form submit' : 'Interaction',
      isSynced: true,
      currentTrackingStatus: i === 0 ? 'Page view only' : 'No tracking',
      improvementHint: 'AI suggests detailed interaction monitoring',
      screenshotReference: `https://images.unsplash.com/photo-${i % 2 === 0 ? '1460925895917-afdab827c52f' : '1581291589057-df151324730b'}?auto=format&fit=crop&q=80&w=800`,
      components: components
    };
  });
};

const REVIEW_JOURNEY_NAMES = [
  '5G UW Upgrade Flow', 'Disney+ Activation', 'Global Nav Refresh', 'B2B Portal Login', 
  'Apple Watch Setup', 'Trade-in Value Checker', 'Fios TV Remote', 'Auto-Pay Opt-in',
  'Cloud Storage Upsell', 'Verizon Up Refresh', 'Store Appointment', 'Unlimited Plans',
  '5G Home Guide', 'Secure Cloud Login', 'Cart Recovery', 'Device Onboarding',
  'Loyalty Tier Status', 'Small Biz Onboarding', 'Promotion Opt-out', 'Equipment Return Tracker'
];

const EXISTING_JOURNEY_NAMES = [
  'Global Navigation', 'Homepage Search', 'Support Chat Flow', 'Bill Pay Lifecycle',
  'Auto-Pay Enrollment', 'Plan Comparison Matrix', 'Store Locator', 'Contact Us Form',
  'Account Profile Update', 'Device Protection Signup', '5G Coverage Map', 'Visible Migration',
  'Business Fiber Inquiry', 'Cloud Backup Setup', 'Verizon Up Rewards', 'Pre-paid Activation',
  'International Roaming', 'Multi-line Discount', 'Referral Program', 'Return & Exchange'
];

export const mockJourneys: Journey[] = [
  {
    journeyId: 'add-a-line',
    journeyName: 'Add a line',
    category: 'Plan',
    icon: Plus,
    platform: 'Web',
    environmentLink: 'https://vzw.com/plans/add-a-line/staging',
    trackingFocus: 'Conversion',
    autoGeneratedGoal: 'Optimize the Add a Line journey to reduce drop-offs between plan selection and checkout.',
    status: 'In progress',
    lastUpdated: '2 hours ago',
    lastUpdatedBy: 'Abhinav Saxena',
    metrics: [{ label: 'Completion Rate', value: '64.2%' }, { label: 'Step Drop-off', value: '12.4%' }],
    steps: generateRealisticSteps('Add a line', 24),
    tagRecommendationCount: 24,
    source: 'Analytics + Data Layer Sync'
  },
  
  ...REVIEW_JOURNEY_NAMES.map((name, i) => {
    const targetTags = name === '5G UW Upgrade Flow' ? 38 : (Math.floor(Math.random() * 20) + 15);
    const steps = generateRealisticSteps(name, targetTags);
    const actualTagCount = steps.reduce((sum, s) => sum + (s.components?.length || 0), 0);
    
    return {
      journeyId: `rev-${i + 1}`,
      journeyName: name,
      category: ['Sales', 'Retention', 'Engagement', 'Business', 'Service'][i % 5],
      icon: [Zap, Package, Globe, User, Smartphone, RefreshCcw, Settings, CreditCard, Layers, MessageSquare, MapPin, Wifi, ShieldCheck, ShoppingCart, Truck][i % 15],
      platform: ['Mobile', 'Web', 'Hybrid'][i % 3] as any,
      environmentLink: i % 2 === 0 ? 'figma.com/file/vzw' : 'jira.atlassian.com/vzw',
      trackingFocus: ['Conversion', 'Engagement', 'Drop-off reduction'][i % 3] as any,
      autoGeneratedGoal: `AI-optimized goal for ${name}: Streamline interactions and capture detailed behavioral telemetry.`,
      status: 'Not started' as any,
      sourceType: (i % 2 === 0 ? 'Figma' : 'Jira') as any,
      source: i % 2 === 0 ? 'Figma Design' : 'Jira Ticket',
      jiraContext: {
        ticketId: `CX-${1000 + i}`,
        title: `Measure ${name} Performance`,
        reference: `https://jira.verizon.com/browse/CX-${1000 + i}`,
        description: `Implement end-to-end measurement for the ${name} workflow to identify friction points and optimize the conversion funnel.`,
        acceptanceCriteria: [
          'Track all primary CTA clicks',
          'Capture form field validation errors',
          'Measure time-to-complete configuration',
          'Log all external partner redirects',
          'Monitor API response success rates for key actions'
        ]
      },
      tagRecommendationCount: actualTagCount,
      lastUpdated: `${i + 1} hours ago`,
      lastUpdatedBy: 'System Sync',
      metrics: [
        { label: 'Forecasted ROI', value: `${(Math.random() * 15 + 5).toFixed(1)}%` },
        { label: 'Tag Confidence', value: '94%' }
      ],
      steps: steps
    };
  }),

  ...EXISTING_JOURNEY_NAMES.map((name, i) => {
    const targetTags = Math.floor(Math.random() * 25) + 12;
    const steps = generateRealisticSteps(name, targetTags);
    const actualTagCount = steps.reduce((sum, s) => sum + (s.components?.length || 0), 0);
    
    return {
      journeyId: `ext-${i + 1}`,
      journeyName: name,
      category: ['Service', 'Sales', 'Growth', 'Retention'][i % 4],
      icon: [Globe, Search, MessageSquare, DollarSign, CreditCard, Layers, MapPin, FileText, User, ShieldCheck, Wifi, RefreshCcw, Activity, HardDrive, Headset][i % 15],
      platform: ['Web', 'Mobile'][i % 2] as any,
      environmentLink: `https://verizon.com/${name.toLowerCase().replace(/\s/g, '-')}`,
      trackingFocus: ['Engagement', 'Conversion', 'Service'][i % 3] as any,
      autoGeneratedGoal: `Maintain measurement health for ${name} across all production environments.`,
      status: 'Completed' as any,
      sourceType: 'System' as any,
      source: 'Data Layer + Analytics Discovery',
      tagRecommendationCount: actualTagCount,
      lastUpdated: `${i + 2} days ago`,
      lastUpdatedBy: 'Analytics Sync',
      metrics: [
        { label: 'Tracking Health', value: '98%' },
        { label: 'Active Alerts', value: '0' }
      ],
      steps: steps
    };
  })
];